### ISSUE TITLE
Sprint 3 reviews

### ISSUE THREAD

**Issue by SupriyaAdep** [greyatom-school/the-minerva-project#10]
Hi,
Sprint 3 touches all important concepts in Javascript.
Additionally :
a) How our code is executed in the browser and how javascript engine works will be helpful
b) Variable scope now covers hoisting in javascript, additional information on execution context and how scope is created can give better understanding of internals of javascript.
c) Closure linked article explains IIFE in it's example, but this concept is not mentioned in functions chapter.

Thanks
Supriya Adep

**Comment by shettayyy** [comment]
Thank you. Changes have been incorporated.

**Comment by volcas** [comment]
Hey Rahul,
Thanks for the incorporation. 

Internally learning team recently identified an issue- 
The first link in concept 1.1(Intro_to_js_variables_and_operators) is dead now. Would be great if we can replace the same.

You can close the issue after that
Thanks

**Comment by shettayyy** [comment]
Done
