### ISSUE TITLE
[Paid] Data Structures And Algorithms Made Easy: Data Structure And Algorithmic Puzzles by Narasimha Karumanchi

### ISSUE THREAD

**Issue by shettayyy** [greyatom-school/the-minerva-project#3]
The student would have to pay for the book. It doesn't seem fair if he has already subscribed to GreyAtom. We already have a lot of free resources. Maybe an additional section can be added to list paid resources with a tag like [PAID].

Let's avoid paid resources.

https://www.amazon.com/Data-Structures-Algorithms-Made-Easy/dp/819324527X

**Comment by karanrshah96** [comment]
Made the neccessary changes.
